// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {verify} from '../models';

export function GetAcceptedDocs():Promise<Array<verify.VerificationDocument>>;

export function GetPendingDocuments():Promise<Array<verify.VerificationDocument>>;

export function GetRejectedDocuments():Promise<Array<verify.VerificationDocument>>;

export function Greet(arg1:string):Promise<string>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function LoginUserTest():Promise<boolean>;

export function LoginVerifierTest():Promise<boolean>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<void>;
