// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {blockchain} from '../models';
import {models} from '../models';

export function ApproveDocument(arg1:number,arg2:string):Promise<void>;

export function GetAcceptedDocs():Promise<Array<blockchain.VerificationDocument>>;

export function GetAllDocs():Promise<Array<blockchain.VerificationDocument>>;

export function GetFilePath():Promise<string>;

export function GetPendingDocuments():Promise<Array<blockchain.VerificationDocument>>;

export function GetRejectedDocuments():Promise<Array<blockchain.VerificationDocument>>;

export function IsApprovedInstitute():Promise<boolean>;

export function IsLoggedIn():Promise<boolean>;

export function IssueCertificate(arg1:models.CertificateData):Promise<void>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function Logout():Promise<void>;

export function Register(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function TryDecrypt(arg1:Array<number>,arg2:string,arg3:string):Promise<Array<number>>;

export function UploadDocument(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ViewDocument(arg1:string,arg2:string,arg3:string):Promise<string>;
