// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {blockchain} from '../models';

export function GetAcceptedDocs():Promise<Array<blockchain.VerificationDocument>>;

export function GetAllDocs():Promise<Array<blockchain.VerificationDocument>>;

export function GetPendingDocuments():Promise<Array<blockchain.VerificationDocument>>;

export function GetRejectedDocuments():Promise<Array<blockchain.VerificationDocument>>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RegisterVerifier(arg1:string,arg2:string,arg3:string):Promise<void>;
