// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAcceptedDocs() {
  return window['go']['main']['App']['GetAcceptedDocs']();
}

export function GetPendingDocuments() {
  return window['go']['main']['App']['GetPendingDocuments']();
}

export function GetRejectedDocuments() {
  return window['go']['main']['App']['GetRejectedDocuments']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function LoginUserTest() {
  return window['go']['main']['App']['LoginUserTest']();
}

export function LoginVerifierTest() {
  return window['go']['main']['App']['LoginVerifierTest']();
}

export function Register(arg1, arg2, arg3) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3);
}
