// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveDocument(arg1, arg2) {
  return window['go']['main']['App']['ApproveDocument'](arg1, arg2);
}

export function GetAcceptedDocs() {
  return window['go']['main']['App']['GetAcceptedDocs']();
}

export function GetAllDocs() {
  return window['go']['main']['App']['GetAllDocs']();
}

export function GetFilePath() {
  return window['go']['main']['App']['GetFilePath']();
}

export function GetPendingDocuments() {
  return window['go']['main']['App']['GetPendingDocuments']();
}

export function GetRejectedDocuments() {
  return window['go']['main']['App']['GetRejectedDocuments']();
}

export function IsApprovedInstitute() {
  return window['go']['main']['App']['IsApprovedInstitute']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function Register2(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Register2'](arg1, arg2, arg3, arg4);
}

export function TryDecrypt2(arg1, arg2, arg3) {
  return window['go']['main']['App']['TryDecrypt2'](arg1, arg2, arg3);
}

export function UploadDocument(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadDocument'](arg1, arg2, arg3);
}

export function ViewDocument(arg1, arg2, arg3) {
  return window['go']['main']['App']['ViewDocument'](arg1, arg2, arg3);
}
